version: '3.2'

volumes:
  postgres:
    driver: local

services:
  jira-bot-db:
    image: postgres:13.0
    container_name: jira-bot-db
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    networks:
      - jira-bot-net

  jira-bot-ms:
    container_name: jira-bot
    build:
      context: .
      dockerfile: ./build.dockerfile
    image: jira-bot
    ports:
      - "8082:8082"
    depends_on:
      - jira-bot-db
    environment:
      DB_HOST: jira-bot-db
      DB_PORT: 5437
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - jira-bot-net
networks:
  jira-bot-net:
    driver: "bridge"
