server:
  port: '8082'
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        ws:
          client:
            MessageTracing:
              received: TRACE
          server:
            MessageTracing:
              received: TRACE
url:
  notification-app: ${NOTIFICATION_APP_URL:http://localhost:8080}

bot:
  name: ${BOT_NAME:JiraSubscribeTestingBot}
  token: ${BOT_TOKEN:6236905174:AAGAHoA8u4Q0Gm8fH_I0WehACevppSsnQF4}

