server:
  port: '8082'
logging:
  config: 'classpath:logback.xml'
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        ws:
          client:
            MessageTracing:
              received: TRACE
          server:
            MessageTracing:
              received: TRACE
bot:
  name: JiraSubscribeTestingBot
  token: 6236905174:AAGAHoA8u4Q0Gm8fH_I0WehACevppSsnQF4

log4j:
  appender:
    myappender:
      encoding: UTF-8

url:
  notification-app:
    chat: http://localhost:8080
