CREATE TABLE IF NOT EXISTS CHAT
(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(30),
    TELEGRAM_ID VARCHAR(15),
    TYPE VARCHAR(15),
    STATUS VARCHAR(30),
    CREATED_DATE    TIMESTAMP(6) NOT NULL,
    UPDATED_DATE    TIMESTAMP(6) NOT NULL
)