CREATE TABLE IF NOT EXISTS ISSUE
(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(100),
    ISSUE_KEY VARCHAR(15),
    TYPE VARCHAR(15),
    STATUS VARCHAR(30),
    DESCRIPTION VARCHAR,
    CHAT_ID BIGINT,
    CREATED_DATE    TIMESTAMP(6) NOT NULL,
    UPDATED_DATE    TIMESTAMP(6) NOT NULL
)