CREATE TABLE IF NOT EXISTS COMMENT
(
    ID SERIAL PRIMARY KEY,
    AUTHOR VARCHAR(100),
    DESCRIPTION VARCHAR,
    ISSUE_ID BIGINT,
    JIRA_ID VARCHAR(15),
    CREATED_DATE    TIMESTAMP(6) NOT NULL,
    UPDATED_DATE    TIMESTAMP(6) NOT NULL
)